### ISSUE TITLE
Apple ALC issue and setting HiDPi on 1080p display

### ISSUE THREAD

**Issue by racka98** [i3p9/Hackintosh-BigSur-Catalina-OpenCore-Lenovo-T450s-efi#1]
As i described in the other post [here](https://github.com/EchoEsprit/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi/issues/47#issuecomment-706274357). 

I get white noise when i plug in my headphones right after boot. Only fixed by setting the laptop to sleep. And sound loss too when i unplug my headphones and plug them back in.

So far i haven't been successful with IntelBluetoothFirmware.kext to connect to my bluetooth earbuds. The showed up but disconnect immediately when you pair and sometimes disappear (might open this issue on their Github). Wifi works though.

Also what's the best settings for HiDPi on 1080p display?
Edit: I've fixed the HiDPi issue

**Comment by i3p9** [comment]
For headphones issues, I highly suggest [alc_fix](https://github.com/i3p9/Hackintosh-Catalina-OpenCore-Lenovo-T450s-efi/tree/master/alc_fix), just clone the folder, `chmod +x install.sh` and install it. Should be good to go.

And Bluetooh, it's weird because while I do not use Intel cards (I use Broadcom apple native card) but I did try IntelBluetooth, and it worked pretty good for me. Will you try this [older kext of IntelBluetooth](https://we.tl/t-ALleioADsI) and repot back?
And evidently, when I tried Intel Bluetooth and WiFi, while having WiFi connected, my bluetooth audio would cut out so much that it wasn't listenable at all. Do you have the 7265AC card?

Ah just noticed you've fixed the HiDPi issue, personally I use 1440x910 for shapness and screen real estate.

**Comment by racka98** [comment]
Will try the alc fix again and see. 


I've read more about the intelbluetooth thing i do experience the cut out when i use bt + wifi. But work fine without wifi enabled. 

However I've noticed that the boot times are very long and there's some noticable lag with animations when resizing windows, opening dialog boxes ans scrolling in some apps. Do you notice any of these??

Checking in verbose mode i saw something related to Intelfirmware that hangs for a very long time. Even removing the intel wifi and bluetooth kexts Intelfirmware still hangs during boot

**Comment by i3p9** [comment]
> However I've noticed that the boot times are very long and there's some noticable lag with animations when resizing windows, opening dialog boxes ans scrolling in some apps. Do you notice any of these??

Boot times are fairly okay for me considering it's a hackintosh I never really reboot my laptop other than for updates and stuff. As for the scrolling lag, what kind of SSD do you have? Most times it's because of GPU or shitty dram-less ssd's.

> Checking in verbose mode i saw something related to Intelfirmware that hangs for a very long time. Even removing the intel wifi and bluetooth kexts Intelfirmware still hangs during boot

after removing intelfirmware, rebuild kext cache and do a nvram reset.

**Comment by racka98** [comment]
> > However I've noticed that the boot times are very long and there's some noticable lag with animations when resizing windows, opening dialog boxes ans scrolling in some apps. Do you notice any of these??
> 
> Boot times are fairly okay for me considering it's a hackintosh I never really reboot my laptop other than for updates and stuff. As for the scrolling lag, what kind of SSD do you have? Most times it's because of GPU or shitty dram-less ssd's.
> 
> > Checking in verbose mode i saw something related to Intelfirmware that hangs for a very long time. Even removing the intel wifi and bluetooth kexts Intelfirmware still hangs during boot
> 
> after removing intelfirmware, rebuild kext cache and do a nvram reset. 

I have an Intel Pro 2500 series SSD. Pretty sure it has a dram. And the lag only happens on a few non native apps like MS Edge, PlistEditor, MS office

**Comment by i3p9** [comment]
> I have an Intel Pro 2500 series SSD. Pretty sure it has a dram. And the lag only happens on a few non native apps like MS Edge, PlistEditor, MS office

I don't know about MS Edge or Office, but Plist Editor takes like 2 seconds to open, even on my beefy iMac at work so it's definitely just the app.

**Comment by racka98** [comment]
> > I have an Intel Pro 2500 series SSD. Pretty sure it has a dram. And the lag only happens on a few non native apps like MS Edge, PlistEditor, MS office
> 
> I don't know about MS Edge or Office, but Plist Editor takes like 2 seconds to open, even on my beefy iMac at work so it's definitely just the app.

Yeah might just be the apps since it does happen in all native apps and other downloaded apps like IntelliJ or Android studio
